# NumPy - Zadania

* Dokumentacja NumPy: http://docs.scipy.org/doc/numpy/reference/
* Tutorial NumPy: https://docs.scipy.org/doc/numpy-dev/user/quickstart.html

## Zadania 1.1

1. Za pomocą jednowierszowego polecenia utwórz następującą macierz:
$a =
\begin{pmatrix}
1       & 2      & \cdots & 10      \\
11      & 12     & \cdots & 20      \\
\vdots  & \ddots & \ddots & \vdots  \\
41      & 42     & \cdots & 50 
\end{pmatrix}$
2. Za pomocą metod obiektu `array`: 
 * określ liczbę elementów, kolumn i wierszy,
 * stwórz wektory średnich po wierszach oraz po kolumnach,
 * wypisz trzecią kolumnę macierzy `a`.
3. Przetestuj i opisz w jednym zdaniu działanie następujących funkcji: 
 * `np.log(a)` 
 * `np.cumsum(a)`
 * `np.rank(a)`
 * `np.power(a,2)`
4. Stwórz wektor składający się z 50 losowych punktów z przedziału 14 do 31

In [2]:
# tutaj wpisz swoje rozwiązania zadań 1.1
import numpy as np

#1
a = np.arange(1,51).reshape(5,10)
print("#1")
print(a)
print("\n")

#2
a_size = a.size
a_rows, a_columns = a.shape
column_mean = a.mean(axis=0) # średnia po kolumnach
row_mean = a.mean(axis=1) # średnia po wierszach
print("#2")
print("elements: %d, rows: %d, columns: %d" % (a_size, a_rows, a_columns))
print("mean of columns: %s; mean of rows: %s" % (str(column_mean), str(row_mean)))
print("third column %s" % str(a[:,2]))
print("\n")

#3
np.log(a) # logarytm naturalny każdego elementu
np.cumsum(a) # cumulative sum, w kaźdej komórce znajduje się suma tego elementu i elementów występujących wcześniej
np.ndim(a) # zwaraca liczbę wymiarów, np.rank zostało wycofane (is deprecated)
np.power(a,2) # każdy element tablicy podnosi do kwadratu

#4
vec = np.random.uniform(14,32,50)
#lub np.random.randint(14,32,50) jeśli chodziło o całkowite, bo trochę polecenie jest dla mnie nieprecyzyjne
print("#4")
print(vec)

#1
[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48 49 50]]


#2
elements: 50, rows: 5, columns: 10
mean of columns: [ 21.  22.  23.  24.  25.  26.  27.  28.  29.  30.]; mean of rows: [  5.5  15.5  25.5  35.5  45.5]
third column [ 3 13 23 33 43]


#4
[ 23.11001609  24.77708831  30.25452629  22.10703563  26.6923972
  21.46177332  31.34460572  18.17005656  23.22198156  24.09894957
  22.55700331  19.88201246  21.64813574  24.11212763  14.76546667
  23.52037397  27.85775933  18.88858216  30.41237988  28.76332762
  23.09998264  30.9439832   20.8670449   21.84979786  29.01893035
  24.00693458  16.10578072  17.73376662  23.17296578  14.13383799
  19.85336714  14.24163314  20.63442481  29.67429424  17.96779856
  29.79207396  25.29328449  19.78059061  23.06649467  20.81412093
  15.61746054  28.48073809  19.56983581  20.98761461  17.64382058
  20.74591681  28.37408893  28.59299113  14.674

## Zadania 1.2

Zapisz i oblicz za pomocą NumPy
1. Iloczyn macierzy $A$ z wektorem $\vec{x}$:
$$\begin{align*}
  A \vec{x} &= \left[
    \begin{array}{rrr}
      1 & -1 & 2\\
      0  & -3 & 1
    \end{array}
  \right]
  \left[
    \begin{array}{l}
      2\\1\\0
    \end{array}
  \right]
  =
  \left[
    \begin{array}{r}
      1\\
      -3
    \end{array}
  \right].
\end{align*}$$

2. Iloczyn macierzy $A$ i $B$:  
$$\begin{align*}
  AB &=\left[
      \begin{array}{rrr}
        0 & 4 & -2\\
        -4 & -3 & 0
      \end{array}
    \right] 
    \left[
      \begin{array}{rr}
        0 &1\\
        1 & -1\\
        2 & 3
      \end{array}
    \right]
    =
    \left[
      \begin{array}{rr}
        0 & -10\\
        -3 & -1
      \end{array}
    \right].
  \end{align*}$$
  
3. Pokaż, że dla powyższych macierzy $A$ i $B$ prawdą jest, że $(AB)^T = B^TA^T$.  
4. Oblicz $\det(AB)$ (wyznacznik iloczynu $AB$).
4. Czym różni się operacja `A**-1` dla obiektów typu `array` i `matrix`? Pokaż na przykładzie. 
6. Dla macierzy $X = \left[
      \begin{array}{rrr}
        1 & 2 & 3\\
        1 & 3 & 6 \\
      \end{array}
    \right]$ oraz wektora $\vec{y} = \left[
      \begin{array}{r}
        5 \\
        6 \\
      \end{array}
    \right]$ oblicz wynikowy wektor: 
$$\vec{\theta} = (X^TX)^{-1}X^T\vec{y}.$$ Wykonaj te same obliczenia raz na obiektach typu `array` i raz na obiektach typu `matrix`. W przypadku obiektów typu `matrix` zastosuj możliwie krótki zapis. 

In [18]:
# tutaj wpisz swoje rozwiązania zadań 1.2
import numpy as np

#1
A = np.array([[1,-1,2],[0,-3,1]])
x = np.array([2,1,0])
C = np.dot(A,x)
print("#1")
print(C)
print("\n")

#2
A = np.array([[0,4,-2],[-4,-3,0]])
B = np.array([[0,1],[1,-1],[2,3]])
C = np.dot(A,B)
print("#2")
print(C)
print("\n")

#3
C = np.dot(A,B).T
D = np.dot(B.T,A.T)
is_equal = np.array_equal(C,D)
print("#3")
print(is_equal)
print("\n")

#4
detAB = np.linalg.det(np.dot(A,B))
print("#4")
print(detAB)
print("\n")

#5
A_arr = (np.array([[1,2],[3,4]])).astype(float)
A_matr = np.matrix([[1,2],[3,4]])

print("#5")
print(A_matr**-1)
print(A_arr**-1)
print("\n")

# Różnica jest taka, że dla obiektu array operator ** każdy element kolekcji podnosi do danej potęgi (w tym przypadku -1), 
# dla obiektu matrix natomiast wyznacza macierz odwrotną.

#6
X_arr = np.array([[1,2,3],[1,3,6]]).astype(float)
y_arr = np.array([[5],[6]]).astype(float)
theta_arr = np.dot(np.dot(np.linalg.inv(np.dot(X_arr.T,X_arr)),X_arr.T),y_arr)

X_matr = np.matrix([[1,2,3],[1,3,6]])
y_matr = np.matrix([[5],[6]])
theta_matr = ((X_matr.T*X_matr)**-1)*X_matr.T*y_matr

print("#6")
print(theta_arr)
print(theta_matr)

#1
[ 1 -3]


#2
[[  0 -10]
 [ -3  -1]]


#3
True


#4
-30.0


#5
[[-2.   1. ]
 [ 1.5 -0.5]]
[[ 1.          0.5       ]
 [ 0.33333333  0.25      ]]


#6
[[-7.    ]
 [ 2.5   ]
 [ 0.0625]]
[[-7.    ]
 [ 2.5   ]
 [ 0.0625]]
